### ISSUE TITLE
No administration after installation

### ISSUE THREAD

**Issue by tofeo** [YunoHost-Apps/friendica_ynh#10]
The .htconfig has no admin email 
$a->config['admin_email'] = '';

You cannot go to administration of your friendica,

**Comment by Josue-T** [comment]
Hello,

It look like related to this line https://github.com/YunoHost-Apps/friendica_ynh/blob/master/scripts/install#L113

**Comment by anmol26s** [comment]
The script is not adding the admin email?
Can you show the logs please, it would be helpful to know why the email is not being added or there maybe some other issue.

**Comment by anmol26s** [comment]
@Josue-T 

Can you help? 

The complete command is : 

ynh_replace_string "$a->config['admin_email'] = '';" "$a->config['admin_email'] = '$admin_mail';" "$final_path/.htconfig.php"

But the command is giving error because of `$a->` as it looks $a as variable.

**Comment by anmol26s** [comment]
Unfortunately it don't work :(
I tested it on testing branch. Any other suggestion? I think I will have to use sed command here.

**Comment by Josue-T** [comment]
Mybe try that : `ynh_replace_special_string`.

**Comment by anmol26s** [comment]
This too did not worked. :(

**Comment by Josue-T** [comment]
Ok in this case are you sure that your expression match with the file contents ?

**Comment by anmol26s** [comment]
Yes, expression changed in the latest release thats why it started failing on latest sources.
See this : https://github.com/friendica/friendica/blob/2018.05/htconfig.php#L70

**Comment by MrPetovan** [comment]
`.htconfig.php` file has been deprecated in the latest stable version, the new `config/local.ini.php` should be easier to handle.

**Comment by anmol26s** [comment]
The testing branch is having final test so that it can be merged into master.
The .htconfig.php will be removed and local.ini.php will be added when upgrading from version < 2018.09

https://github.com/YunoHost-Apps/friendica_ynh/blob/testing/scripts/upgrade#L48-L57

**Comment by anmol26s** [comment]
This issue should be fixed now with version 2018.09 merged into master.

**Comment by Josue-T** [comment]
Hello,

After the upgrade to friendica 2018.09, I lost my admin access in my admin account

**Comment by Josue-T** [comment]
After some investagtion I discovered that I don't have any app setting named "admin_email". It's probably because friendica has been installed before this commit 572070c216dbab565c6772c10fbe0255d57e479e . I think you should manage this case in your script. If I add my admin email manually in `/var/www/friendica/config/local.ini.php` it fix the issue.

**Comment by anmol26s** [comment]
@Josue-T 
Can you show the logs? The email is saved in setting.yml before this commit too and is called in update to replace inthe configuration file.

**Comment by Josue-T** [comment]
Here is my a extract of my friendica settings : 
```
# cat /etc/yunohost/apps/friendica/settings.yml 
admin: yunoadmin
apt_dependencies: php-mbstring
checksum__etc_nginx_conf.d_social.tille.ch.d_friendica.conf: MYSHECKSUM
checksum__etc_php5_fpm_conf.d_20-friendica.ini: MYSHECKSUM
checksum__etc_php5_fpm_pool.d_friendica.conf: MYSHECKSUM
checksum__etc_php_7.0_fpm_conf.d_20-friendica.ini: MYSHECKSUM
checksum__etc_php_7.0_fpm_pool.d_friendica.conf: MYSHECKSUM
checksum__var_www_friendica_.htconfig.php: MYSHECKSUM
checksum__var_www_friendica_config_local.ini.php: MYSHECKSUM
db_name: friendica
domain: domain.tld
final_path: /var/www/friendica
fpm_config_dir: /etc/php/7.0/fpm
fpm_service: php7.0-fpm
id: friendica
install_time: 1514067585
is_public: '1'
label: Friendica
mysqlpwd: MYPASSWORD
path: /
skipped_uris: /
unprotected_uris: /
update_time: 1539601607
```

**Comment by anmol26s** [comment]
Ok, then you have the admin field. I think previous versions use to store the admin field rather then the email. 
I will update the upgrade script so that if email field is empty then the admin field can be used to get email.
Thanks for reporting this.
