### ISSUE TITLE
Backup not working - missing cron.d/friendica

### ISSUE THREAD

**Issue by hermann-san** [YunoHost-Apps/friendica_ynh#114]
### Describe the bug

When I try to backup Friendica, there is an error message and the backup stopps
WARNING - Source path '/etc/cron.d/friendica' does not exist

Manually creating a friendica directory or file in that path doesn't help to backup successfully. 

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.4 (stable).
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### Steps to reproduce

1.start Friendica backup
2. error message appears

### Expected behavior
Backup successful

### Logs

WARNING - Source path '/etc/cron.d/friendica' does not exist

https://paste.yunohost.org/raw/gunonofepe

**Comment by Zeitverschreib** [comment]
I have the very same issue when trying to update to 2023.05-ynh3.

**Comment by orhtej2** [comment]
You need to `touch` this file, the problem is solved in newer version

**Comment by hermann-san** [comment]
@orhtej2  I did create that file, but the problem persists.

**Comment by orhtej2** [comment]
> @orhtej2 I did create that file, but the problem persists.

Can you please share logs of failing update from after recreating said file?

**Comment by Zeitverschreib** [comment]
After touching the file, I was able to run a backup and also upgrade the instance.

**Comment by hermann-san** [comment]
@orhtej2  I've used nano to create the file, but apparently there is a difference with touch. That worked. Thanks.
