### ISSUE TITLE
Upgrading to 2023.05~ynh3 fails at backup due to mySQL error 1412

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/friendica_ynh#116]
### Describe the bug

When upgrading to 2023.05~ynh3 via the admin panel, the upgrade fails during the pre-upgrade backup due to an Error 1412:

> Error 1412: Table definition has changed, please retry transaction when dumping table `inbox-entry` at row: 0

### Context

- Old laptop or computer
- YunoHost version: 11.2.4
- I have access to my server: Physically, via the webadmin, and via SSH if needed
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2023.05~ynh3
- If upgrading, current package version: 2022.10~ynh1 (although the admin panel within Friendica reports 2023.01)

### Steps to reproduce

Update Friendica from the System Update panel in YunoHost admin.

### Logs

[Log available here](https://paste.yunohost.org/raw/unodolehop)

**Comment by Zeitverschreib** [comment]
Have you set the instance to maintenance mode before starting the backup/upgrade?

**Comment by tio-trom** [comment]
Is this issue still relevant?
