### ISSUE TITLE
Creating new admin account after fresh installation: please update Yunohost's instructions

### ISSUE THREAD

**Issue by cgKAF** [YunoHost-Apps/friendica_ynh#118]
As I wrote [here](https://forum.yunohost.org/t/friendica-logging-in-as-admin-after-new-installation/28034) on the Yunohost forum, please could the advice given in the Yunohost Admin Panel for Friendica be updated so it gives accurate instructions on what users should do to create the first user on their account with admin privileges?

Currently, after installing Friendica, in Yunohost Admin Panel > Applications > Friendica, there is a section that reads:
> #### User with LDAP admin rights
>
> For admin rights: When installation is complete, you will need to visit your domain page and login with the admin account username and password which was entered at the time of installation process. You can then create your profile and access the admin panel.

I went through the installation process last week and it does not ask for any input from the user.

After installation, the admin user has to create an account (they can’t log in) on their newly-installed Friendica server using their Yunohost administrator username and email address (not their password) and a Friendica account will be created with admin privileges built in. The password is emailed to their Yunohost administrator's email address and they then use this to log in, before changing it to something of their own choosing.

**Comment by OniriCorpe** [comment]
added a post install message explaining how to login: https://github.com/YunoHost-Apps/friendica_ynh/blob/master/doc/POST_INSTALL.md
