### ISSUE TITLE
Friendica URL uses // and crashes in contacts menu

### ISSUE THREAD

**Issue by cgKAF** [YunoHost-Apps/friendica_ynh#119]
### Describe the bug

Copying the issue from the [Yunohost Forum](https://forum.yunohost.org/t/friendica-uses-after-hostname-in-url-following-installation-making-app-fail-partially/28154); posting on Eolab's behalf. They believed this may be linked to their Friendica account not federating properly with Mastodon and other ActivityPub servers (which I also had trouble with), but I'm not sure of this.

Friendica-YNH creates a URL that uses a double forward slash after the domain name; e.g. `https://www.domain.tld//network`. Mostly the site works, but directs the user to `https://contacts/` on reaching the Contacts page rather than the expected `https://www.domain.tld/contacts/`.

This *may* be connected to [this issue](https://github.com/YunoHost-Apps/friendica_ynh/issues/85).

### Context

- Hardware: Old laptop/computer (Intel based)
- YunoHost version:  11.2.9.1
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using Friendica 2023.05~ynh3

### Steps to reproduce

- Install Friendica, set up admin account and log in
- Go to the 'Contacts' page in the top (icon of three people)
- Either there, or in one of the tabs in the bottom left (Friends, Followers, Following, etc.), should lead you to the non-existent page `https://contacts/`.

### Expected behaviour

Friendica should have only one forward slash between the domain and the network in the URL, and the contacts (and login) pages should display as expected.

**Comment by OniriCorpe** [comment]
hi!

this should be fixed with 2023.12~ynh2
