### ISSUE TITLE
Corrupt source for friendica 2018.09

### ISSUE THREAD

**Issue by Josue-T** [YunoHost-Apps/friendica_ynh#13]
Hello,

When I tried to upgrade friendica I got a corrupt source error : here is my result of my checksum : 
```
➜  /tmp wget -nv -O app.zip https://github.com/friendica/friendica/archive/2018.09.zip
2018-10-09 21:42:15 URL:https://codeload.github.com/friendica/friendica/zip/2018.09 [17761168] -> "app.zip" [1]
➜  /tmp md5sum app.zip 
ab58be32f7bedcc41e124b6b77ebc427  app.zip
```

**Comment by anmol26s** [comment]
This is weird they have changed the sources of the version 5 days ago. Friendica should have released a minor release to fix rather then changing the sources of major release.
https://github.com/friendica/friendica/releases/tag/2018.09

Anyways I am on to it. Will update to new sources in next hour after a test.

**Comment by Josue-T** [comment]
Thanks,

Note that md5 is actually not considered as really robust. It should be better to use sha256.

**Comment by anmol26s** [comment]
I have updated checksum with sha256 for the latest release 2018.09.
I hope everything goes well on upgrade now.

Thanks
