### ISSUE TITLE
Upgrade to latest version

### ISSUE THREAD

**Issue by pubmania** [YunoHost-Apps/friendica_ynh#17]
Hi,

Please can this be upgraded to the latest version of Friendica... Their site says Jan 2019 is latest stable release.

**Comment by Josue-T** [comment]
Found that there are a testing version of the version 2019.1. Is it functional ?

**Comment by anmol26s** [comment]
Hi @pubmania 

Sorry for the delay for this release. The app is now upgraded to latest version.

Closing this issue.

**Comment by pubmania** [comment]
@anmol26s  Thanks for the upgrade but something did not go right here as after upgrade the login page appears but then 504 Gateway Time-out error appears. 😕

**Comment by anmol26s** [comment]
Can you try to upgrade again?

**Comment by pubmania** [comment]
I tried upgrading from terminal using the command ```sudo yunohost app upgrade friendica``` but that just showed following:
```
Info: Upgrading apps friendica
Info: Upgrading app friendica…
Success! friendica is already up to date
Error: No app to upgrade
```
No option to upgrade from fronted either.

How can I upgrade it again please?

**Comment by anmol26s** [comment]
There is an issue going on Yunohost. You can try the below command and see if it work : 

`$ yunohost app upgrade -u https://github.com/YunoHost-Apps/friendica_ynh/tree/3396188976f75170f2217fcc0e6c9b5f61f7b9e9 friendica --debug`

**Comment by pubmania** [comment]
Hi.. it worked in the sense that it upgraded again but hasn't resolved the error ...
