### ISSUE TITLE
DB need update when migration to 2019.01

### ISSUE THREAD

**Issue by Josue-T** [YunoHost-Apps/friendica_ynh#18]
Hello,

I saw that when we upgrade friendica to the version 2019.01 we need to update the database. To do that I did it manually in the admin pannel. But I think it could be useful to do that automatically on the upgrade or to add this information in the README.

**Comment by anmol26s** [comment]
As I do not use the Friendica personally. Can you please explain me how you updated the database?
In my test from previous version there was no problem while upgrading to 2019.01.

**Comment by Josue-T** [comment]
Yes, the upgrade don't fail, but until the migration is done, friendica don't work really well dans tall all my CPU...

To do that as I said, I did it on the web admin of friendica in the admin panel I have a page named something like "DB update", (I don't know really well the exact name because It depends of the theme and of the language). in this page I have a link named "check database structure", but maybe you have something else before to do the upgrade.

**Comment by anmol26s** [comment]
Ok I understand, but I am not sure if this is related to this upgrade or there is some other issue while upgrade. Sometimes the DB upgrade fails for no reason as I have seen this with Hubzilla and it has to manually upgrade. 

But still I will add this in readme.

**Comment by Josue-T** [comment]
Maybe we can force the db update as documented here : https://github.com/friendica/friendica/releases/tag/2019.06

With this command:

```
bin/console dbstructure update
```

**Comment by anmol26s** [comment]
I will add this in next update. 
Thanks

**Comment by tio-trom** [comment]
Is this issue still relevant now?
