### ISSUE TITLE
Please upgrade to 19.04

### ISSUE THREAD

**Issue by Josue-T** [YunoHost-Apps/friendica_ynh#20]
The 19.04 version of friendica is out.

Is it possible to upgrade the package

**Comment by ironm0nk3y** [comment]
Hello, currently package in multiple versions behind. Can you update package or possibly document how we can go about doing so individually if we would like? Thanks!

**Comment by Josue-T** [comment]
The version 19.06 is already out...

**Comment by TheNomad11** [comment]
That's the drawback with Yunohost. It is convenient but the price you have to pay is using outdated versions. For this reason I do not want to use it for serious stuff, but only for testing

**Comment by Josue-T** [comment]
> That's the drawback with Yunohost. It is convenient but the price you have to pay is using outdated versions. For this reason I do not want to use it for serious stuff, but only for testing

Well, not all app are not up to date. I'm the packager too, and I try to keep all my apps up to date.

**Comment by TheNomad11** [comment]
Yes, some are up to date and generally the apps are ok, but the thing is you cannot rely on that. I also see that some apps fall in rating, one day they are rated 7, the next one only two (Etherpad f.ex), and some suddely stop being maintained. From a user perspective this is far from satisfactory

**Comment by SpencerDub** [comment]
The latest version is [19.12](https://github.com/friendica/friendica). Is there any chance this repository could be updated to reflect the new version?

**Comment by tobiasd** [comment]
Which PHP version is currently available on Yunohost systems? Since the [2019.03 release](https://friendi.ca/2019/03/22/friendica-2019-03-dalmatian-bellflower-released/) Friendica requires PHP7 prior to the release PHP5.6 was enough.

**Comment by Josue-T** [comment]
Actually php7.0

**Comment by tobiasd** [comment]
Ok, then updating the package should be possible. I have at the moment no YunoHost system near me and have only briefly worked with it before, so my hints might go into the wrong direction and break things. ;-)

* There is the `manifest.json` file and the `README.md`in the root directory of this package. Where the current version number has to be raised to adopt the correct one. Probably the change in the `README.md` file is not necessary for testing this, but if you to a pull request to update this repository, then you should change the version there as well.
* In the `/conf` directory there is the `/conf/addons.src` file where you find `SOURCE_URL` and `SOURCE_SUM`. The URL for the addons file of the 2019.12 release is `https://github.com/friendica/friendica-addons/archive/2019.12.tar.gz` and the SUM is `c206a8b0845a4a5102b5a9d1881d039472d734c70d5f1dd52e44684955b6a7f2` (just download the archive and run the command `sha256sum 2019.12.tar.gz`)
* Then in `/conf/app.src` the corresponding fields. The URL is `https://friendi.ca/wp-content/uploads/2019/12/friendica-full-2019.12.tar.gz` and the SUM is `6affca62ba26ba34f809a2b1db6612090bb7e0cf5d39bde6e7cbabd1c080ade9`

If all goes well, then these changes should be enough to raise Friendica on YH to the current stable release. If there is some brave YH user to test this, good luck ;-) let us know how it worked out.

Updating over multiple versions across should be working fine in this case between 2019.01 and 2019.12 we had not breaking stuff in the configuration of Friendica. The conservative way would be to apply the above changes for every release step-wise, just adopt the checksums and URLs accordingly.. And there was a performance issue solved in the 2019.03 release of Friendica which might lead to higher resource consumption; then the current worker settings need to be adopted in the admin panel (less worker required to do the same jobs).

**Comment by tobiasd** [comment]
Just saw https://github.com/YunoHost-Apps/friendica_ynh/blob/master/scripts/install#L80 so you need to update the PHP5 dependencies in this package configuration for the corresponding PHP7 dependencies as well.

**Comment by SpencerDub** [comment]
@tobiasd, thanks for checking this out and providing that list!

**Comment by SpencerDub** [comment]
I've started a PR (#22) to upgrade this. If anyone else has the time or know-how, *please* jump on!

**Comment by SpencerDub** [comment]
I think #22 is ready for testing.

**Comment by SpencerDub** [comment]
I tried to install the new version using #22, but the script encountered an error. I've pasted the log starting at the first warning [here](https://pastebin.com/wb6Nwe1w), but the issue appears to be this:

> WARNING -   End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.

I'm not sure how to resolve this.

**Comment by SpencerDub** [comment]
I've sidestepped that by simply using `2019.12.zip` and the corresponding checksum. Haha, lateral thinking!

(Still curious if using something like `SOURCE_FORMAT=tar.gz` or `SOURCE_FORMAT=gz` would have done the trick too, though.)

This version of the installation script completed properly and installed Friendica. I'm still experimenting, though, to see if it's all configured properly.

**Comment by SpencerDub** [comment]
I've reached another challenge, and I'm not sure what to do with it. I'd welcome the help of anyone who's available and might understand the Friendica setup process better than I do (@tobiasd?).

My installation of Friendica 2019.12 on YunoHost using my installation script seems not to recognize what its URL is. If you go to https://friendica.xanderwharts.us/friendica, you can see that the installation is not properly reporting the web location, and just reports "http://". Also, and I presume this is related, when I try to use the "login" button (at https://friendica.xanderwharts.us/login), it just redirects to https://login. It's as if the installation did not properly configure the "what's my URL?" setting for Friendica.

I could use the assistance of anyone who understands more about YunoHost and/or Friendica.

**Comment by tobiasd** [comment]
Uninstalling and reinstalling of the app sounds unintended by YH. Though great that it worked this way.

The `hostname` configuration value in `/config/local.confg.php` should point to your domain (without http(s)) and from there it is tajen for the links.

**Comment by SpencerDub** [comment]
The peculiar thing is that after uninstalling v2019.12, I actually installed the old version still in the YH app catalog. That went off without a problem. Then I uninstalled and reinstalled via my script, which also worked.

It makes sense that it worked; as far as I can tell, I didn't change anything between the v2019.01 and v2019.12 install scripts related to setting the hostname. Not sure what happened the first time around, though. 🤷

**Comment by anmol26s** [comment]
I have updated the app to version 2020.03. Sorry for delay. It was really a pain for me to not to update the app for a while.
It would be nice if this could be closed now. 
Thanks

**Comment by Jaxom99** [comment]
I encounter the same issue as @SpencerDub, but on 2020.03 on a fresh 3.8 ynh install.

> My installation of Friendica 2019.12 on YunoHost using my installation script seems not to recognize what its URL is. If you go to https://friendica.xanderwharts.us/friendica, you can see that the installation is not properly reporting the web location, and just reports "http://". Also, and I presume this is related, when I try to use the "login" button (at https://friendica.xanderwharts.us/login), it just redirects to https://login. It's as if the installation did not properly configure the "what's my URL?" setting for Friendica.

Is there anything we can do to help ? Maybe this belongs to another ticket...
