### ISSUE TITLE
Changing Admin User's e-mail removes admin rights

### ISSUE THREAD

**Issue by Doc-Saintly** [YunoHost-Apps/friendica_ynh#23]
Steps to reproduce:
1. Install Friendica Application
2. Set User1 as Admin
3. Log in as User1
4. Change e-mail address to a different one
5. The admin settings icon disappears

Tried to change the e-mail back and it gives the error 

> Cannot change to that email.

Only solution seems to be to uninstall and re-install.

A workaround is to use a dedicated admin user for Friendica and do not change the e-mail address.

Another workaround is to manually change the local.config.php file:
>  'admin_email' => ...

**Comment by anmol26s** [comment]
The `'admin_email' =>` is added while installation. This is default feature. Once the admin rights are given to a user its responsibility of the admin to take care of this type of issues. 

We can give a warning about this in the readme. I will add this in next update.

For a solution  the admin email in the app settings can be changed and upgrade the app, which will change the admin email, thus giving back the admin rights to a user.

**Comment by tio-trom** [comment]
Is this issue still relevant? If so please feel free to reopen.
