### ISSUE TITLE
[buster] Dependencies gotta be updated

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/friendica_ynh#25]
The install is currently failing because of php-mcrypt missing (which probably can be safely remove).

Also I doubt that we need to keep the "php**5**" stuff, the app is probably not installable on jessie anymore anyway, considering that the upstream now requires php7.x and that the app scripts seem to be using recent helpers ? So the manifest.json should be updated to require Yunohost >= 3.x

**Comment by anmol26s** [comment]
I have updated the version to 2020.03. We can pull the @yalh76 PR when its ready. 
The php5 stuff have been removed.

**Comment by yalh76** [comment]
Just have to test if authentication other ldap is still ok

**Comment by yalh76** [comment]
> 
> 
> I have updated the version to 2020.03. We can pull the @yalh76 PR when its ready.
> The php5 stuff have been removed.

The PR is ready, I let you do the merge

**Comment by yalh76** [comment]
PR is OK
