### ISSUE TITLE
White page after upgrade

### ISSUE THREAD

**Issue by pintman** [YunoHost-Apps/friendica_ynh#29]
After upgrading to the lastet version I got the following error in my logs and the page stays white.

https://paste.yunohost.org/oqevafiyid

**Comment by anmol26s** [comment]
Can you enable the php.log for the friendica?

**Comment by pintman** [comment]
Here is the pgp-log.

https://paste.yunohost.org/neqayuloyi.sql

**Comment by anmol26s** [comment]
Upgrade the app once again.

**Comment by pintman** [comment]
I don't get any information about available updates in the update section. Currently installed version is 2020.03-ynh2.

**Comment by anmol26s** [comment]
`$ yunohost app upgrade -u https://github.com/YunoHost-Apps/friendica_ynh friendica --debug`

**Comment by pintman** [comment]
Still the same problem.

The output of the command can be found here: https://paste.yunohost.org/iturukiguh.sql

**Comment by c-cesar** [comment]
The problem is `vendor/level-2/dice/Dice.php:249`.
The file uses `::getName()` because `::__toString()` has been deprecated, but YNH uses a old PHP that don't supports `::getName()`.
We can patch, or use a new PHP version, like with Nextcloud.

**Comment by tio-trom** [comment]
Is this issue still relevant? If so please reopen it.
