### ISSUE TITLE
Update to 2020.09

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/friendica_ynh#32]
The app is currently v2020.03.

[Friendica v2020.09 has been released](https://friendi.ca/2020/09/20/friendica-2020-09-released/), so the install script needs to be updated appropriately.

Apparently, 2020.07 has [an issue with PHP 7.0](https://forum.friendi.ca/display/3e3ce0df-865f-0d6e-992d-679374230100). Newer versions of PHP are apparently supported by Debian Buster, which [YunoHost 4.0 now runs on](https://forum.yunohost.org/t/yunohost-4-0-buster-release-sortie-de-yunohost-4-0-buster/12195).

**Comment by SpencerDub** [comment]
Alright, I might be able to dig into this soon if someone can give me pointers.

The previous update I made to this script, following [Tobias' guide](https://github.com/YunoHost-Apps/friendica_ynh/issues/20#issuecomment-576122167) only involved changing the sources and checksums of installation files. Will that suffice for this, or will more extensive changes be necessary? If more extensive changes are needed, what are they?

@anmol26s, do you know what it would take to update this package to Friendica v2020.07?

**Comment by blackfireburn** [comment]
I tried to fork it and replaced the php 7.0 values with the 7.3 but while it installs and the packages are correct, it won't let me log in. I haven't had time to did into it unfortunately.

**Comment by SpencerDub** [comment]
There's a new upstream security release, [v2020.07-1](https://friendi.ca/2020/09/08/hotfix-release-of-friendica-2020-07-1/) that makes this upgrade even more pressing.

Additionally, I expect that Friendica 2020.09 will be released before the month is out, since it's currently in the release candidate phase.

**Comment by ben-utzer** [comment]
For Friendica we now have tar archive available for docker installations, but these probably could be used for yunohost too. The files are hosted here: https://files.friendi.ca/
This is maintained by @tobiasd

Also I would like to add that an update is really suggested due to some security issue in 03.2020 and actually in 07.2020 before 07.2020-1, which allows access to session information and hence to admin sessions and then to all accessible information in the backend as far as I understood. 

Maybe for the future Friendica for yunohost can fetch the github stable branch of Friendica regularly or trigger able by the YunoHost admin?

**Comment by SpencerDub** [comment]
Friendica [v2020.09](https://friendi.ca/2020/09/20/friendica-2020-09-released/) has now been released.

**Comment by tobiasd** [comment]
The idea with the archive files is that, there is a VERSION file in the stable branch of Friendica (e.g. https://git.friendi.ca/friendica/friendica/src/branch/stable/VERSION, you can use the file on github as well) and for the version mentioned in that file, there will be 2 tar archives on files.friendi.ca

* friendica-addons-VERSION.tar.gz 
* friendica-full-VERSION.tar.gz  

in addition, there are `*.sum256` files that contain the SHA256 checksum for the archive files.

So ideally you just need to adjust the [app.src](https://github.com/YunoHost-Apps/friendica_ynh/blob/master/conf/app.src#L1) and [addons.src](https://github.com/YunoHost-Apps/friendica_ynh/blob/master/conf/addons.src#L1) with the new fixed file location and exchange the version number after each release.

**Comment by SpencerDub** [comment]
I've forked this repo and made changes to the sources and checksums. I've tested it as an upgrade to an existing installation and it seems to have worked without a hitch.

In the future, I'm happy to update checksums and file sources like this--that's work that I'm easily able to do. However, if anything ever changes in the installation/upgrade process beyond those simple tasks, I do not currently have the know-how to either recognize or address that. For that reason, I'm fine being a sort of "semi-maintainer" for this repo, but I don't want to be relied upon as the sole maintainer, because I don't have the independent knowledge or skill to be a good steward.

**Comment by Torenga** [comment]
>I've tested it as an upgrade to an existing installation and it seems to have worked without a hitch.

How do you upgrade?

**Comment by tiotrom** [comment]
So this Friendica addon has no maintainer anymore?

**Comment by SpencerDub** [comment]
@Torenga - From the command line. `sudo yunohost app upgrade friendica -u [URL to Git archive]` directed YunoHost to upgrade the app from the specified URL.

@tiotrom - I don't know who's maintaining friendica_ynh here. I will likely continue making changes to my own fork, which will work until an upgrade requires anything more complicated than changing checksums and URLs. I'm not a knowledgeable dev, though, so I can't encourage anyone to rely on my fork.

**Comment by anmol26s** [comment]
I will do some tests and push the PR on weekend.

**Comment by tiotrom** [comment]
I love friendica and we are testing yunohost which is 100% amazing! So if Friendica keeps on being maintained and updated then we could create more instances of it, quicker, via yunohost. I wish I knew how to help. Thank you to all so much for your work!

**Comment by tiotrom** [comment]
We would be so happy to provide yet another friendica node but this is 1 year old and may not work well. So if you can update it and maintain it, would be so amazing and I could not thank you enough. :)
