### ISSUE TITLE
Archive files

### ISSUE THREAD

**Issue by tobiasd** [YunoHost-Apps/friendica_ynh#33]
Not a real issue, just wanted to let you know: the Friendica project now has an [archive for released versions](https://files.friendi.ca) holding the friendica-full and friendica-addons archives as tar.gz files. Maybe you can use that location for downloading the packages.

The filenames will stay in the current schema `friendica-full-[VERSION}.tar.gz` and `friendica-addons-{VERSION}.tar.gz `. Checksums are available in the `*.sum256` files.

**Comment by anmol26s** [comment]
Thanks for this.
