### ISSUE TITLE
My YNH installs the old version

### ISSUE THREAD

**Issue by tiotrom** [YunoHost-Apps/friendica_ynh#40]
I just tested with my YNH, all updated, but still installs the old version.

**Comment by tiotrom** [comment]
More to that, it did not create any user for me so I cannot administrate it. Here are the logs: https://paste.yunohost.org/raw/imideqepis

**Comment by anmol26s** [comment]
You have to use testing branch.

`yunohost app upgrade -u https://github.com/YunoHost-Apps/friendica_ynh friendica --debug`

Beware that Ldap is broken in the latest release. Please make the backup before upgrading.

**Comment by tiotrom** [comment]
It worked. Thanks!

**Comment by tiotrom** [comment]
It worked. Thanks!
