### ISSUE TITLE
The new version, failed to install

### ISSUE THREAD

**Issue by tiotrom** [YunoHost-Apps/friendica_ynh#43]
Here's the entire log https://paste.yunohost.org/raw/iqinozabiw

**Comment by anmol26s** [comment]
The composer should be inside the app folder itself. Have you tried installing again?

**Comment by tiotrom** [comment]
Just tried again. Failed again. https://paste.yunohost.org/raw/hoziliwato

**Comment by tiotrom** [comment]
I had it installed before on the same domain. Then I manually upgraded it to the https://github.com/SpencerDub/friendica_ynh with Spencer's help. All worked fine. Then I got a message from ynh that there is a new version of freindica  from ynh. I upgraded it. And it didn't work properly. I decided to remove it entirely and reinstall. And that's where I'm at now. :D 
 
Should I try to reinstall on another domain?

**Comment by anmol26s** [comment]
Can you try to install with :

`$ yunohost app install --debug  https://github.com/SpencerDub/friendica_ynh `

**Comment by tiotrom** [comment]
How would it know on what domain it will install? I don't want to do anything bad to our ynh server.

**Comment by anmol26s** [comment]
You can install on any free domain.

**Comment by tiotrom** [comment]
Ok that worked! Great. But did not create an automated account for me, so how am I dealing with the admin rights?

**Comment by tiotrom** [comment]
Here's the log:
```
sudo yunohost log display 20210212-202159-app_install-friendica
description: Install the 'friendica' app
log_path: /var/log/yunohost/categories/operation/20210212-202159-app_install-friendica.log
logs: 
  - 2021-02-12 21:23:22,341: DEBUG - + local value
  - 2021-02-12 21:23:22,341: DEBUG - + ynh_handle_getopts_args --app=friendica --key=unprotected_uris --value=/
  - 2021-02-12 21:23:22,341: DEBUG - + set +o xtrace
  - 2021-02-12 21:23:22,442: DEBUG - + [[ unprotected_uris =~ (unprotected|protected|skipped)_ ]]
  - 2021-02-12 21:23:22,442: DEBUG - + yunohost app setting friendica unprotected_uris -v /
  - 2021-02-12 21:23:23,044: WARNING - /!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.
  - 2021-02-12 21:23:26,461: DEBUG - + ynh_script_progression '--message=Reloading nginx web server...'
  - 2021-02-12 21:23:26,461: DEBUG - + set +o xtrace
  - 2021-02-12 21:23:26,462: DEBUG - + set +o xtrace
  - 2021-02-12 21:23:26,462: DEBUG - + echo '! Helper used in legacy mode !'
  - 2021-02-12 21:23:26,462: DEBUG - + set +x
  - 2021-02-12 21:23:26,462: DEBUG - + echo '[################++..] > Reloading nginx web server...'
  - 2021-02-12 21:23:26,463: DEBUG - + set -o xtrace
  - 2021-02-12 21:23:26,463: DEBUG - + ynh_systemd_action --service_name=nginx --action=reload
  - 2021-02-12 21:23:26,463: DEBUG - + local legacy_args=nalpte
  - 2021-02-12 21:23:26,463: DEBUG - + args_array=([n]=service_name= [a]=action= [l]=line_match= [p]=log_path= [t]=timeout= [e]=length=)
  - 2021-02-12 21:23:26,463: DEBUG - + local -A args_array
  - 2021-02-12 21:23:26,464: DEBUG - + local service_name
  - 2021-02-12 21:23:26,464: DEBUG - + local action
  - 2021-02-12 21:23:26,464: DEBUG - + local line_match
  - 2021-02-12 21:23:26,464: DEBUG - + local length
  - 2021-02-12 21:23:26,464: DEBUG - + local log_path
  - 2021-02-12 21:23:26,465: DEBUG - + local timeout
  - 2021-02-12 21:23:26,465: DEBUG - + ynh_handle_getopts_args --service_name=nginx --action=reload
  - 2021-02-12 21:23:26,465: DEBUG - + set +o xtrace
  - 2021-02-12 21:23:26,666: DEBUG - + service_name=nginx
  - 2021-02-12 21:23:26,666: INFO - [################++..] > Reloading nginx web server...
  - 2021-02-12 21:23:26,667: DEBUG - + action=reload
  - 2021-02-12 21:23:26,667: DEBUG - + line_match=
  - 2021-02-12 21:23:26,667: DEBUG - + length=20
  - 2021-02-12 21:23:26,667: DEBUG - + log_path=/var/log/nginx/nginx.log
  - 2021-02-12 21:23:26,667: DEBUG - + timeout=300
  - 2021-02-12 21:23:26,668: DEBUG - + [[ -n '' ]]
  - 2021-02-12 21:23:26,668: DEBUG - + '[' reload == reload ']'
  - 2021-02-12 21:23:26,668: DEBUG - + action=reload-or-restart
  - 2021-02-12 21:23:26,668: DEBUG - + systemctl reload-or-restart nginx
  - 2021-02-12 21:23:26,869: DEBUG - + [[ -n '' ]]
  - 2021-02-12 21:23:26,870: DEBUG - + ynh_script_progression '--message=Installation of friendica completed'
  - 2021-02-12 21:23:26,870: DEBUG - + set +o xtrace
  - 2021-02-12 21:23:26,971: DEBUG - + set +o xtrace
  - 2021-02-12 21:23:26,972: DEBUG - + echo '! Helper used in legacy mode !'
  - 2021-02-12 21:23:26,972: DEBUG - + set +x
  - 2021-02-12 21:23:26,972: DEBUG - + echo '[##################++] > Installation of friendica completed'
  - 2021-02-12 21:23:26,973: DEBUG - + set -o xtrace
  - 2021-02-12 21:23:26,973: DEBUG - + ynh_exit_properly
  - 2021-02-12 21:23:26,973: DEBUG - + local exit_code=0
  - 2021-02-12 21:23:26,974: DEBUG - + '[' 0 -eq 0 ']'
  - 2021-02-12 21:23:26,974: DEBUG - + exit 0
  - 2021-02-12 21:23:27,009: DEBUG - Checking that required services are up and running...
  - 2021-02-12 21:23:28,014: SUCCESS - Installation completed
metadata: 
  args: 
    app: https://github.com/SpencerDub/friendica_ynh
    args: None
    force: False
    label: None
    no_remove_on_failure: False
  ended_at: 2021-02-12 21:23:28
  env: 
    YNH_APP_ARG_ADMIN: tio
    YNH_APP_ARG_DOMAIN: social.trom.tf
    YNH_APP_ID: friendica
    YNH_APP_INSTANCE_NAME: friendica
    YNH_APP_INSTANCE_NUMBER: 1
    YNH_APP_MANIFEST_VERSION: 2021.01~ynh1
  error: None
  interface: cli
  operation: app_install
  parent: None
  related_to: 
    - app
    - friendica
  started_at: 2021-02-12 21:21:59
  success: True
  yunohost_version: 4.1.7.1
metadata_path: /var/log/yunohost/categories/operation/20210212-202159-app_install-friendica.yml
name: 20210212-202159-app_install-friendica
```

**Comment by tiotrom** [comment]
`YNH_APP_ARG_ADMIN: tio`
Although it says this, I was unable to login with user tio and my ynh password, or using the recover password said user "tio" is not found. I was also able to register a new user "tio" just to check. But ofc, this is a normal user, not admin.

**Comment by anmol26s** [comment]
I think your email should match the admin email(which was given while installation process). Or have you tried login with email? The Ldap is broken in the latest release. See here
https://github.com/YunoHost-Apps/friendica_ynh/pull/34#issuecomment-726135096
 Till someone dig deep into the LDAP issue, its not going to get resolved soon.
You can try other alternatives like Mastodon, Palorma, Miskkey, Hubzilla, Zap, Osada, Writefreely, Plume, Funkwhale, Pixelfed and Nextcloud.

**Comment by tiotrom** [comment]
Yes I tried with the email...doesn't work. It is a shame since Friendica is so good, the best federated social network I found. Modern looking, connects with pretty much anything (including twitter, rss, and so forth). So we would really love to provide our instance for anyone to use, via ynh.

Since it installed ok, isn't there a way to force a user to become admin? From the command line?

**Comment by anmol26s** [comment]
I have tested it and I can confirm that admin panel is available to the user to whom admin privileges was provided at the time installation.
After login just add /admin in front of your domain.

**Comment by tiotrom** [comment]
I reinstalled it. Same issue. What am I doing wrong? I tried to login with my email and username....nothing. I even clicked to reset the password, added my email or user, and says there is no account found with these....

**Comment by tiotrom** [comment]
I installed it on a different domain. Again. Same issue.

**Comment by anmol26s** [comment]
Change the admin email in ` $var/www/friedica/config/local.config.php ` .

**Comment by tiotrom** [comment]
Well the weird part is that the email is there....the correct one. But if I try to reset the password from the friendica instance here: social.trom.tf - it says email tio@trom.tf is not a valid account found....what is happening?

**Comment by anmol26s** [comment]
While doing new sign up, you need to enter correct email i.e tio@trom.tf. Are you entering the mail correctly? How do know that you don't have admin access?

**Comment by tiotrom** [comment]
Oh wow hold on this was very very confusing. I am sorry. Maybe it is my fault, but maybe it is worth mentioning in the Readme. 

So. Friendica remembers your user email that you use when you install it. It remembers it. But that's all. You have to then create a new account with that same email. After you create the account you get a password in the email, and have to login again. And yes, now I am admin.

It was confusing honestly. I thought that once I install Friendica it will create a new user with the email of the user I chose for the installation. But it does not, I had to register a new account with that email.

In any case it works now. I am sorry for the confusion, but maybe it is worth updating the readme page.

**Comment by anmol26s** [comment]
@tiotrom Feel free to open a PR for this.

**Comment by tiotrom** [comment]
I would if I knew how... I have no idea.

**Comment by isAAAc** [comment]
i just made a PR to explain howto connect and trying to make it more clear

https://github.com/isAAAc/friendica_ynh/pull/1

**Comment by isAAAc** [comment]
https://github.com/YunoHost-Apps/friendica_ynh/pull/65
