### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/friendica_ynh#45]
Was happy to see that Friendica is being maintained now. Tried to install it without luck, though. Here are the logs:

https://paste.yunohost.org/raw/xusocobecu

**Comment by EvilOlaf** [comment]
Confirmed.
https://paste.yunohost.org/raw/ocovotucof

**Comment by kaerdon** [comment]
Hello,
i confirm this error.
**The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly**
https://paste.yunohost.org/raw/nalayodojo

**Comment by kaerdon** [comment]
Hello i solved it by using command line yunohost app install command
yunohost app install --debug https://github.com/SpencerDub/friendica_ynh
and it worked

**Comment by EvilOlaf** [comment]
Confirmed. Console install works.

**Comment by kaerdon** [comment]
yes after go in system update and it will update to the new

**Comment by EvilOlaf** [comment]
Admin interface seems broken though...
