### ISSUE TITLE
Files/Folders with 0777 file permission

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/friendica_ynh#46]
```
/var/www/friendica/vendor/bin/phpunit
/var/www/friendica/vendor/bin/certainty-cert-symlink
/var/www/friendica/vendor/bin/parallel-lint
/var/www/friendica/vendor/bin/html-to-markdown

```

**Comment by anmol26s** [comment]
Have you tried changing the file permission? Last time changed the permission to 755, it broke Friendica.

**Comment by TROMsite** [comment]
Not yet bcs I am afraid to break Friendica. We can also ask the Friendiuca dev about it https://github.com/friendica/friendica/issues/10053
