### ISSUE TITLE
Upgrade to version 2021.07 ? :)

### ISSUE THREAD

**Issue by TROMsite** [YunoHost-Apps/friendica_ynh#52]
We have asked in a previous post to update to 2021.04 and you did so thank you! It just so happened that Friendica released a new version today which ads support for the Mastodon API, which means Friendica can be used with any Mastodon client. Which is really useful for people who use smartphones. So, if possible to upgrade to the newest one...that'd be great! Thanks again!

https://git.friendi.ca/friendica/friendica/src/branch/stable/CHANGELOG

**Comment by ericgaspar** [comment]
As this package uses `git pull` to upgrade the app I believe you can try:
`sudo yunohost app upgrade friendica -u https://github.com/YunoHost-Apps/friendica_ynh/tree/testing --force`
or wait for the *patch* branch to be tested and merged...

**Comment by TROMsite** [comment]
Thanks! I may wait for the patch branch since I don't want to break my Friendica again. I really hope I can upgrade my friendica instance eventually :).

**Comment by ericgaspar** [comment]
closing with #55
