### ISSUE TITLE
Upgrade to 2021.07~ynh2 broke Friendica very bad

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/friendica_ynh#59]
- Hardware: *VPS bought online*
- YunoHost version: 4.2.6.1 (stable).
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*

Ok so here are the logs https://paste.yunohost.org/raw/ocadocefiw

After the upgrade a few things happened:

1.  I lost the Admin access. As simple as that I had no admin rights.
2. No local photos were displaying, only photos coming from other servers.
3. The custom themes from friendica/view/frio/scheme that I made were deleted

I had to restore to a previous Friendica, the one before the git upgrade.

**Comment by TROMsite** [comment]
These 2 may be related, idk https://github.com/friendica/friendica/issues/10375 and https://github.com/friendica/friendica/issues/10443

**Comment by TROMsite** [comment]
I have tried with this possible fix: https://github.com/mr-eshua/friendica_ynh/tree/fix-git-upgrade

Here is the log:
```
sudo yunohost app upgrade friendica -u https://github.com/mr-eshua/friendica_ynh/tree/fix-git-upgrade --force
Info: Now upgrading friendica...
Info: [+...................] > Loading installation settings...
Info: [#+++................] > Ensuring downward compatibility...
Info: [####++..............] > Backing up the app before upgrading (may take a while)...
Info: [######+.............] > Making sure dedicated system user exists...
Info: [#######+++..........] > Upgrading source files...
Warning: File /var/www/friendica/config/local.config.php has been manually modified since the installation or last upgrade. So it has been duplicated in /home/yunohost.conf/backup//var/www/friendica/config/local.config.php.backup.20210721.040035
Warning: --- /home/yunohost.conf/backup//var/www/friendica/config/local.config.php.backup.20210721.040035	2021-02-27 18:22:26.138698000 +0100
Warning: +++ /var/www/friendica/config/local.config.php	2021-07-21 04:00:36.315068017 +0200
Warning: @@ -32,9 +32,9 @@
Warning:  	// ****************************************************************
Warning:  	'config' => [
Warning: -		'admin_email' => '*********',
Warning: +		'admin_email' => '*************',
Warning:  		'sitename' => 'Friendica Social Network',
Warning: -		'register_policy' => \Friendica\Module\Register::CLOSED,
Warning: +		'register_policy' => \Friendica\Module\Register::OPEN,
Warning:  		'register_text' => '',
Warning:  	],
Warning:  	'system' => [
Info: [##########+.........] > Upgrading NGINX web server configuration...
Info: [###########++.......] > Upgrading PHP-FPM configuration...
Info: [#############+......] > Upgrading Cron configuration...
Info: [##############++++..] > Upgrading DB structure...
Info: [##################+.] > Reloading NGINX web server...
Info: [####################] > Upgrade of friendica completed
Success! friendica upgraded
Success! Upgrade complete
```

And the output is that Friendica is dead :) 
![image](https://user-images.githubusercontent.com/38043315/126419011-5f7ebeb9-639d-446f-88f1-b8081d634e50.png)

I am restoring it now. Thanks for trying and maybe the logs will help you.

**Comment by anmol26s** [comment]
Can you send the php logs when this happened?  Did you had the custom theme when you last updated? And was it deleted then too?

I would suggest that first restore from snapshot. Then try to move the entire friendica to git manually. To be honest I had not tested the app manually. We strongly believe in continuous integration tests. Which was passing.

**Comment by mr-eshua** [comment]
We managed to upgradeour instance successfully with this fix: https://github.com/YunoHost-Apps/friendica_ynh/pull/60

**Comment by TROMsite** [comment]
Yup finally! @mr-eshua fixed it and now all seems to work! So awesome!

**Comment by tio-trom** [comment]
This fixed my friendica https://github.com/YunoHost-Apps/friendica_ynh/pull/60 please merge the pull
