### ISSUE TITLE
Mobile version of 2021.09 on Android : gives "502 Bad Gateway"

### ISSUE THREAD

**Issue by takemusu1160** [YunoHost-Apps/friendica_ynh#63]
Since 2021.09 install : 

- no problem on desktop nor firefox/chrome android version in "desktop mode"
- but either firefox/chrome mobile version gives "502 Bad Gateway" error.

### Context

- Hardware: *VPS bought online
- YunoHost version: 4.2.8.3
- I have access to my server: *Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

**Comment by tio-trom** [comment]
This is what may have fixed it for us https://github.com/friendica/friendica/issues/10916#issuecomment-955212004  may be too early to tell tho.
