### ISSUE TITLE
Move from CRON to Daemon

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/friendica_ynh#78]
I run an instance with some 800 users and my CPU went from 70% to 30% after we did this change and it is easy to do. Would you be interested?

This is the tutorial about how to do that https://nequalsonelifestyle.com/2022/08/04/setting-up-friendica-daemon-systemd-service/ - we tested it and it is quite easy to do.

**Comment by tio-trom** [comment]
Seems like we need to close this. Thank you @ericgaspar - you are awesome man!

**Comment by MrPetovan** [comment]
Version 2 ended up not including the cron to daemon change because of technical difficulties.

**Comment by tio-trom** [comment]
> Version 2 ended up not including the cron to daemon change because of technical difficulties.

Oh so I got fooled by the previous Daemon that we got implemented and which is active and works on our server. Uh...ok. I will double check that.

**Comment by tio-trom** [comment]
The implementation may not have worked properly. I opened a new issue here https://github.com/YunoHost-Apps/friendica_ynh/issues/133
