### ISSUE TITLE
2022.10~ynh1 is actually 2022.12-dev 

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/friendica_ynh#82]
I have upgraded my friendica and upgraded to 2022.12-dev .... despite the package being labeled as 2022.10~ynh1. Please see where the mistake is in pulling the friendica files. You should pull from stable.

**Comment by tio-trom** [comment]
> wrong commits in scripts/_common.sh
> 
> it should look like this
> 
> version_commit="7109d2a6a8924e8cec7735017fdc00bb1af38b8c" addons_version_commit="408a62a9a16d2613ab37bc9e5dabf5fd63b36b73"

Can you do a pull request maybe?

**Comment by brockhaus** [comment]
Sorry to ask, but what is the state of the friendica-ynh version right now as 2022-12 is in RC already?
Looking at git status in /var/www/friendica really looks strange:

```
/var/www/friendica# git status
On branch stable
Your branch is ahead of 'origin/stable' by 442 commits.
  (use "git push" to publish your local commits)

```

Will this be updated to a "proper version"? Or can we update our self by switching to the release branch maybe?

**Comment by tio-trom** [comment]
This what has to be done in my view:

1. Switch this package to the latest Friendica RC release, since this version of the ynh package uses a random dev release. Here's the RC https://friendi.ca/2022/12/06/friendica-2022-12-release-candidate-avail-able/
2. Properly label the YNH package as RC Friendica.
