### ISSUE TITLE
Cannot backup Friendica before upgrade.

### ISSUE THREAD

**Issue by KanenasPL** [YunoHost-Apps/friendica_ynh#84]
### Describe the bug

*An attempt to upgrade from previous version unsuccessful with internal error (cannot backup previous version).*

### Context

- Hardware: *Old laptop or computer *
- YunoHost version: 11.0.10.2
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

Previous version: 2022.06~ynh1

Upgrading to: 2022.10~ynh1
### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough.*
    ```sh
    sudo yunohost app upgrade friendica
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*
      DONE

### Logs

Logs: https://paste.yunohost.org/raw/uhuhidosid
Error message from GUI
![Screenshot_20221123_184237](https://user-images.githubusercontent.com/114858632/203616866-b48af5eb-8aee-420e-8da2-d220fd0adbe6.png)

**Comment by Zeitverschreib** [comment]
I'm getting the same error when trying to back up an existing 2022.12 instance:

`Info: Backing up the MySQL database...
Warnung: mysqldump: Error 1412: Table definition has changed, please retry transaction when dumping table `workerqueue` at row: 0`

What can I do?

**Comment by EssmannMa** [comment]
connect to the server via ssh and with `sudo su`  become root then change to the directory /var/www/friendica and execute the command `bin/console maintenance 1` . 
The command puts the Friendica in maintenance mode and stops the database. 

then you should be able to make a backup via the web interface as usual.

Is the backup created Friendica again with the command `bin/console maintenance 0` from the maintenance mode back.

**Comment by KanenasPL** [comment]
Thank you. All clear.
