### ISSUE TITLE
2022-12-ynh1 is no 2022-12?

### ISSUE THREAD

**Issue by brockhaus** [YunoHost-Apps/friendica_ynh#88]
Today I saw the the update to 2022-12-ynh1 and did it.

* My theme was removed
* Addons I added where removed too
* I am no admin anymore (local config was reverted)

Why are these things done while _upgrading_? 

But I am missing features from 2022-12. 
* When I look into the yunohost application list, Friendica is listed as 2022.12~ynh1.
* But when I look into the admin menu of the installed friendica it shows version "Friendica 'Giant Rhubarb' 2023.03-dev - 1502"
What is happening here? What version is that? 2023-03? A time traveler? :-D

**Comment by brockhaus** [comment]
Hmm. 2023-03 seems to be the next (unreleased) version when checking the CHANGELOG fille.. But it is 5 commit after stable (and 2022-12).. The most strange: It is missing features like the new image grind for attached images..

**Comment by asherpen** [comment]
No, it happened again... 😭

**Comment by brockhaus** [comment]
Forget it.. It is not the 2022-12 (but an unreleased follower) but the problems seem to be more caching related..

**Comment by brockhaus** [comment]
@asherpen Yes, it seems to be some kind of mess or at least no "defined" stable version, but maybe it is not that bad as it first lokked like.
But I stopped that now. I checked out origin/stable and won't allow any YNH update of my friendica installation again. This is really too unreliable for my taste sadly.. (But thanks for all the work done with this releases!)
