### ISSUE TITLE
Error when uploading images

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/friendica_ynh#9]
Hello

I have tried to upload images in Friendica and I get Nginx 404 not found when I try to open it after upload.

**Comment by Rafi594** [comment]
I have do this and the upload now works but I have no avatars at the top of my screen and my contacts.

![](https://framapic.org/fW5ocBp6T5ip/1Csk297eOGTG.png?width=200)

**Comment by Rafi594** [comment]
I have a blank page when I go to the image link https://social.rafi59.codelib.re/photo/99620553075b2bcabe494ce804593930-6.jpg?ts=1529596609

**Comment by anmol26s** [comment]
I have done few changes in the nginx.
Please update the with: 
`yunohost app upgrade --debug -u https://github.com/YunoHost-Apps/friendica_ynh/tree/nginx_fix friendica`
and see if it gets fixed.

Thanks in improving the app.

**Comment by Rafi594** [comment]
It works
Thanks

**Comment by Josue-T** [comment]
It's ok for me too. Thanks

**Comment by anmol26s** [comment]
Will merge into master.
closing.
