### ISSUE TITLE
Broken Login In Newly-Installed Friendica

### ISSUE THREAD

**Issue by baslow** [YunoHost-Apps/friendica_ynh#97]
Hi!
I can't be sure that this problem belongs to Yunohost (rather than Friendica) but it seemed like I should ask here.

I’ve just installed Yunohost (11.2.1) on a Linode VPS (4 GB RAM) running Debian 11. I then installed Friendica (2023.01~ynh1), apparently successfully, on friendica.mydomain.org. Documentation indicates that, as administrator, I should be able to login using my Yunohost admin login (or email address) and password. When I attempt to do so, however, the Friendica login page takes me to https://login/ – which, of course, doesn’t exist. When I attempted to sign up for a new login (providing different login name and email address) the registration page sent me to _https://friendica_ which displayed as a blank page.

Friendica seems to be installed and running – but the login (and registration) screens don’t work. Clicking on the information icon on the login screen shows:

> This is Friendica, version 2023.01 that is running at the web location http://. The database version is 1502/1502, the post update version is 1484/1484.

(note that it isn't picking up the web location...)

> Installed addons/apps: ldapauth

I checked Services. Yunohost installed Friendica using:

nginx
php7.4-fpm
10.5.19-MariaDB-0+deb11u2

**Comment by OniriCorpe** [comment]
hi!

this should be fixed with 2023.12~ynh2
