### ISSUE TITLE
update to 2023.05, because with the release a security fix was played out.

### ISSUE THREAD

**Issue by sekretaerbaer** [YunoHost-Apps/friendica_ynh#98]
please update to 2023.05, because with the release a security fix was played out.

> ...of Friendica “Giant Rhubarb" 2023.05. This release contains a security fix of a problem @kstrauser pointed out, we strongly encurage all admins to update their nodes. 

https://github.com/friendica/friendica/releases/tag/2023.05

**Comment by tio-trom** [comment]
They just pushed an update. I updated mine and the update went smoothly, however friendica is in maintenance mode and loading forever now https://social.trom.tf/friendica . I saw a message on the Maintenance page "updating post-user table" at one point.... Maybe the database is still updating!? I will wait 20 more minutes if not I will probably restore a snapshot.

**Comment by MrPetovan** [comment]
The message is a sign the database update is running, please do not abort it.

**Comment by tio-trom** [comment]
> The message is a sign the database update is running, please do not abort it.

Yup! Thanks a lot man! I will try it out again because I was unsure if it was ok so I restored a snapshot. Will update if all goes well, or bad :). You really awesome!

**Comment by tio-trom** [comment]
All worked! Thank you so much!

**Comment by MrPetovan** [comment]
This issue is addressed by https://github.com/YunoHost-Apps/friendica_ynh/pull/105
